name: npm-publish

on:
  push:
    branches: [ master ]

jobs:
  build:
  
    name: npm-publish
    runs-on: ubuntu-latest
    
    permissions: 
      contents: read
      packages: write 
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: cd angular/mintplayer-ng-pagination && npm install
    
    - name: Build
      run: npm run build --prefix angular/mintplayer-ng-pagination -- --prod

    - name: Test
      run: npm run test-headless --prefix angular/mintplayer-ng-pagination
    
    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        package: 'angular/mintplayer-ng-pagination/dist/mintplayer/ng-pagination/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v1
      with:
        package: 'angular/mintplayer-ng-pagination/dist/mintplayer/ng-pagination/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'