name: npm-publish-release

on:
  push:
    branches:
      #- 'release/angular**'
      - 'release/dotnet**'

jobs:
  build:
  
    name: npm-publish-release
    runs-on: ubuntu-latest
    
    permissions: 
      contents: read
      packages: write 
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: cd angular/mintplayer-ng-pagination && npm install
    
    - name: Build
      run: npm run nx run-many --prefix angular/mintplayer-ng-pagination -- --target=build --projects=ng-pagination-demo --configuration production

    - name: Test
      run: npm run nx run-many --prefix=angular/mintplayer-ng-pagination -- --target=test --projects=ng-pagination-demo --watch=false --browsers=ChromeHeadless
    
    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        package: 'angular/mintplayer-ng-pagination/dist/libs/mintplayer-pagination/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v1
      with:
        package: 'angular/mintplayer-ng-pagination/dist/libs/mintplayer-pagination/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'