name: pull-request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: pull-request
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    # In a pull request we must make sure both the angular/dotnet library build.

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: 6.0.301
        # Authenticates packages to push to GPR
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'
    
    - name: Install dependencies
      run: dotnet restore dotnet
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}
        
    - name: Build
      run: dotnet build --configuration Release --no-restore dotnet
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal dotnet
      
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: cd angular/mintplayer-ng-pagination && npm install
    
    - name: Build
      run: npm run nx run-many --prefix angular/mintplayer-ng-pagination -- --target=build --projects=ng-pagination-demo --configuration production

    - name: Test
      run: npm run nx run-many --prefix=angular/mintplayer-ng-pagination -- --target=test --projects=ng-pagination-demo --watch=false --browsers=ChromeHeadless
    